ORG 1000H
MSJ DB "INGRESE UN NUMERO:"
NONUM DB "CARACTER NO VALIDO"
FIN DB ?
ORG 1500H
VALOR DB ?

ORG 3000H
ES_NUM:PUSH CX
MOV CH, 030H;Caracter 0
BUCLE: CMP CH, 03AH; Comparo el valor hasta con 9
JZ FINR
CMP VALOR, CH
JZ NUM
INC CH
JMP BUCLE
NUM:MOV DL, 0FFH
FINR:POP CX
RET

ORG 2000H
MOV DL, 0;Registro donde se guarda resultado de la subr
MOV BX, OFFSET MSJ
MOV AL, OFFSET NONUM-OFFSET MSJ
INT 7
MOV BX, OFFSET VALOR
INT 6
CALL ES_NUM
CMP DL, 0;Segun el resultado imprimo o no el mensaje NONUM
JNZ FINP
MOV BX, OFFSET NONUM
MOV AL, OFFSET FIN-OFFSET NONUM
INT 7
FINP:INT 0
END
